dist: jammy
language: php

php:
  - 8.3

node_js:
  - "22"

env:
  matrix:
    - DRUPAL=10.4 PHPUNIT=9
    - DRUPAL=11 PHPUNIT=10

jobs:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  # Install various packages.
  - nvm install 22 && nvm use 22
  - npm install -g gulp-cli

  # Update composer to latest v2.
  - composer self-update --2
  - composer --version

  # Configure the repository authentication mechanisms.
  - if [ "${GITHUB_TOKEN}" != "" ]; then composer config github-oauth.github.com ${GITHUB_TOKEN}; fi
  - if [ "${REPMAN_TOKEN}" != "" ]; then composer config --global --auth http-basic.district09.repo.repman.io token ${REPMAN_TOKEN}; fi

install:
  # Install the module dependencies.
  - composer install -n --no-progress

script:
  - vendor/bin/grumphp run -n
  - cd source && gulp validate && cd ..
